### ISSUE TITLE
No Event rewards

### ISSUE THREAD

**Issue by KamiNasri** [LartTyler/MHWDB-Docs#60] opened 2020-03-02 09:23 UTC
Is it possible to request for Event rewards or just Event special rewards so you could know which events give special tickets etc. Would be a nice improvement.

**Comment by DeveloperPaul123** [comment] 2020-03-02 13:09
This is already logged [here](https://github.com/LartTyler/MHWDB-API/issues/138). Please check the API issues before logging an issue on the documentation repository, otherwise issues regarding the API itself should be filed [here](https://github.com/LartTyler/MHWDB-API/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc). Thanks!

**Comment by LartTyler** [comment] 2020-03-02 13:22
As @DeveloperPaul123 mentioned, this is a duplicate of LartTyler/MHWDB-API#138. The next update should include support for quests, with events including relevant quest information (such as rewards). Your best bet would be to follow the linked issue for updates!

**Closed by LartTyler** 2020-03-02 13:22 UTC
Labels: duplicate
